// src/ai/flows/generate-ai-visuals.ts
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating AI visuals from text.
 *
 * It exports:
 * - `generateAIVisuals`: An async function that takes text input and returns a data URI
 *   containing a base64-encoded PNG image generated by the AI.
 * - `GenerateAIVisualsInput`: The input type for the generateAIVisuals function.
 * - `GenerateAIVisualsOutput`: The return type for the generateAIVisuals function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAIVisualsInputSchema = z.object({
  text: z
    .string()
    .describe(
      'The text to generate visuals from.'
    ),
});
export type GenerateAIVisualsInput = z.infer<typeof GenerateAIVisualsInputSchema>;

const GenerateAIVisualsOutputSchema = z.object({
  imageDataUri: z.string().describe('The generated image as a data URI.'),
});
export type GenerateAIVisualsOutput = z.infer<typeof GenerateAIVisualsOutputSchema>;

export async function generateAIVisuals(input: GenerateAIVisualsInput): Promise<GenerateAIVisualsOutput> {
  return generateAIVisualsFlow(input);
}

const generateAIVisualsPrompt = ai.definePrompt({
  name: 'generateAIVisualsPrompt',
  input: {schema: GenerateAIVisualsInputSchema},
  output: {schema: GenerateAIVisualsOutputSchema},
  prompt: `Given the following text, generate an image that represents it:

Text: {{{text}}}

Image: {{media}}

You must return the image as a data URI string in the imageDataUri field.  The image must be a PNG.
`,
});

const generateAIVisualsFlow = ai.defineFlow(
  {
    name: 'generateAIVisualsFlow',
    inputSchema: GenerateAIVisualsInputSchema,
    outputSchema: GenerateAIVisualsOutputSchema,
  },
  async input => {
    const {media} = await ai.generate({
      model: 'googleai/imagen-4.0-fast-generate-001',
      prompt: input.text,
    });

    return {imageDataUri: media.url!};
  }
);
